language: node_js
dist: jammy

git:
  depth: 1

node_js:
  - '22.9'
  - '24'

install:
  - lmx_skip_postinstall=yes npm ci --no-audit --no-fund

script:
  - npm run compile:check
  - npm run build
  - npm test

notifications:
  email: false
